sudo: requiered
language: php
php:
  - '7.1'
services:
   - docker
before_install:
   - docker-compose up
script:
   - composer install
   - php bin/console doctrine:database:create --env=test
   - php bin/console doctrine:schema:create --env=test
   - php bin/console doctrine:fixtures:load -n --env=test
   - vendor/bin/phpunit